### ISSUE TITLE
Required parameter $imageUrl follows optional parameter $title

### ISSUE THREAD

**Issue by Kashif-Kframe** [realrashid/sweet-alert#108]
- Laravel Version: 8.0

- PHP 7.4

**Description:**
   It says
   Required parameter $imageUrl follows optional parameter $title

   You must need to declare the default value for parameter $imageUrl

  in src/Toastr.php class in image function.

**Comment by Axebaevv** [comment]
I have encountered the same issue! Could you tell us if you have figured out the solution?

**Comment by realrashid** [comment]
Hey 👋,

Can you tell me how you have encountered this error?

Are you trying to call

```php
// example:
alert('Title','Lorem Lorem Lorem', 'success')->addImage('https://unsplash.it/400/200');
```
`addImage()` method?

Or you encountering the error with any alerts.

Please share the steps here this will help me to understand the issue ☺️.

Because I have tested out the package 📦 with Laravel 8.

@Kashif-Kframe @Axebaevv 

Thanks 😊

**Comment by Axebaevv** [comment]
Hi, 

I am using Laravel 8,

I am using the error alert method which was declared in the documentation. 

`public function store(Request $request)
{
    $validator = Validator::make($request->all(), [
        'title' => 'required|min:3',
        'body' => 'required|min:3'
    ]);

    if ($validator->fails()) {
        return back()->with('errors', $validator->messages()->all()[0])->withInput();
    }
    $task = Task::create($request->all());
    return redirect('tasks')->with('success', 'Task Created Successfully!');
    // OR
    return redirect('tasks')->withSuccess('Task Created Successfully!');
}`

And 

`return redirect()->route('projects.index')->with('success', 'Successfully Edited!!!');`

After submitting it shows me  the below error 
"Required parameter $imageUrl follows optional parameter $title"

**Comment by realrashid** [comment]
Hey,

I tested out in the same way as you mention 

```php
$validator = Validator::make($request->all(), [
   'first_name' => 'required',
    'last_name' => 'required',
    'email' => 'required'
 ]);
if ($validator->fails()) {
    return back()->with('errors', $validator->messages()->all()[0])->withInput();
}
```
It wasn't encountered any error as you can see in the attached image below. 

![image](https://user-images.githubusercontent.com/15607685/102773081-73b9f480-43aa-11eb-9a43-fcc34c71e363.png)

The parameter `$imageUrl` is can't be optional because it's a required parameter for two method mention below.

`addImage()`
`image()`

The both method will not invoke automatically until you invoke them.

If you invoke them then you have to pass the required parameters..

If you are still have the same issue with invoking the any of the mention method then I suggest you run the below commands.

```bash
composer dump-autoload
```

```bash
php artisan cache:clear
```

```bash
php artisan sweetalert:publish --force
```

Let me know if it doesn't help.

**Comment by omaisali** [comment]
I have same issue but only on server, working on localhost

@realrashid i tried commands but not working.

**Comment by stefro** [comment]
I also have the same issue. But for me it's working on localhost, but it fails in tests.

**Comment by realrashid** [comment]
Hey 👋,

I had a very busy week 🙏🏻.

I will fix it as soon as I can 👍.

Thanks for letting me know.

**Comment by realrashid** [comment]
Hey,

I have again tested the package in fresh Laravel 8 with Laravel Sail it's working as expected.

![image](https://user-images.githubusercontent.com/15607685/103756952-e1645280-5031-11eb-87a5-f23c03f77bd3.png)

Checkout this screenshot

![image](https://user-images.githubusercontent.com/15607685/103758390-f215c800-5033-11eb-98d5-a509ddccbe7e.png)

Also checkout the video too. 😄 

https://user-images.githubusercontent.com/15607685/103760339-c8aa6b80-5036-11eb-9ad6-ddb2b050da1a.mp4


But as far as your request I will mark that parameter as optional ❤️ .

**Comment by omaisali** [comment]
Please mark that parameter as optional, i am still waiting :)

**Comment by vahiidrah** [comment]
Hi ,I also have the same issue.

**Comment by realrashid** [comment]
Hey 😄 ,

Today I will tag a new release 😃

**Comment by stefro** [comment]
Hi @realrashid 
I can't find this new release anywhere? Is it on a different branch or something? I can't figure out what I'm doing wrong.

**Comment by realrashid** [comment]
Just completed final tests on the updated version of sweetalet.all.js
library.

Tonight I will tag a new release 😉☺️.

**Comment by Benyaminrmb** [comment]
**ErrorException**
**Required parameter $imageUrl follows optional parameter $title**
### 
![image](https://user-images.githubusercontent.com/25666340/104620106-df3e6b80-56a3-11eb-9a87-c0e9f026981d.png)
