### ISSUE TITLE
Return Redirect on Middleware not showing Error type

### ISSUE THREAD

**Issue by rohi1386** [realrashid/sweet-alert#145]
- Package Version: #.#.#
- Laravel Version: #.#.#

### Description:

After following the documentation, when returning/redirecting from middleware the error type does not show the sweetalert. I tried with types success, info, question and warning, they all work.
Steps To Reproduce:

Setup middleware and add ->with('warning', 'Whoops!'); to the return or redirect. It does not show the sweetalert. Test again using ->with('info', 'Whoops!'); and it does work.

(Disclaimer, I am a new to php and laravel so I may be missing something)

### Steps To Reproduce:

**Comment by realrashid** [comment]
Hey @rohi1386,

Please try the below command.

```bs
composer dump-autoload 
```
OR

```bs
php artisan cache:clear
```

**Comment by rohi1386** [comment]
Thanks but it didn't work

**Comment by mohamedds-12** [comment]
It happend to me too, I even tried `alert('title', 'description', 'type')`... but nothing.
One thing worked though, after using the **Sweet-alert**'s middlware to convert the session messages into alerts, I just did
`session()->flash('success', 'Successfully worked!')` **AND IT WORKED**.
But that's still not what I'm looking for because using the session you can't set the `description` of the alert, you're only limited to the `title` and 'type', I'd be happy if someone could get it to work.
