### ISSUE TITLE
Theme dark is broken

### ISSUE THREAD

**Issue by dubbows** [realrashid/sweet-alert#155]
- Package Version: 7.0.0
- Laravel Version: 10.8.0

### Description:
Problem to load style

### Steps To Reproduce:
![Captura de Tela 2023-04-24 às 19 35 49](https://user-images.githubusercontent.com/34485877/234131123-6f1a6129-df6f-406e-bcbf-47f141010b06.png)

**Comment by realrashid** [comment]
Dear,

The dark theme is working but the package has a default white background
you can change it adding SWEET_ALERT_BACKGROUND to your .env to any dark
background.

**Comment by realrashid** [comment]
closed due to inactivity

**Comment by gohari** [comment]
Hi
The theme doesn't work because the background color is set inline style

`
<div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-modal swal2-icon-error swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="width: 32rem; padding: 1.25rem; background: rgb(255, 255, 255); display: grid;">
`
